# Generated by Django 4.1.7 on 2023-06-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=50)),
                ('domiciled', models.BooleanField()),
                ('address', models.CharField(max_length=100)),
                ('number_phone', models.CharField(max_length=20)),
                ('tax_residence', models.CharField(max_length=100)),
                ('type_person', models.CharField(choices=[('1', 'Natural'), ('2', 'Juridico')], max_length=20)),
                ('type_taxpayer', models.CharField(choices=[('1', 'Contribuyente'), ('2', 'No contribuyente')], max_length=20)),
                ('type_sales', models.CharField(choices=[('1', 'Interna'), ('2', 'Exportacion')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
