# Generated by Django 4.1.7 on 2023-04-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('iva', models.FloatField()),
                ('amount_iva', models.FloatField()),
                ('c_ctrl', models.FloatField()),
                ('patente', models.FloatField()),
                ('ret', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('1', 'Registradora con mem. fiscal'), ('2', 'Impresora fiscal'), ('3', 'Computadora con mem. fiscal')], max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('n_invoice', models.CharField(max_length=20)),
                ('zeta', models.CharField(max_length=20)),
                ('since', models.DateTimeField()),
                ('until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('iva_amount', models.FloatField()),
                ('neto_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('branch', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('ctrl_number', models.CharField(max_length=20)),
                ('issuance_date', models.DateField()),
                ('registration_date', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('type_record', models.CharField(choices=[('1', 'Registro'), ('2', 'Complemeto'), ('3', 'Anulación'), ('4', 'Ajuste')], max_length=20)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documenttype')),
                ('provider_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='BuysDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('branch', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=20)),
                ('ctrl_number', models.CharField(max_length=20)),
                ('issuance_date', models.DateField(max_length=20)),
                ('registration_date', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('type_record', models.CharField(choices=[('1', 'Registro'), ('2', 'Complemeto'), ('3', 'Anulación'), ('4', 'Ajuste')], max_length=20)),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='documents.documenttype')),
                ('provider_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='providers.provider')),
            ],
        ),
    ]
