# Generated by Django 4.1.7 on 2023-04-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_buysdocument_items_salesdocument_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysdocument',
            name='items',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='items',
        ),
        migrations.AddField(
            model_name='documentsitems',
            name='buy_document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.buysdocument'),
        ),
        migrations.AddField(
            model_name='documentsitems',
            name='sale_document',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.salesdocument'),
        ),
    ]
