# Generated by Django 4.1.7 on 2023-04-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_type_sales'),
        ('providers', '0002_alter_provider_type_sales'),
        ('documents', '0003_remove_buysdocument_items_remove_salesdocument_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysdocument',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='provider_code',
        ),
        migrations.AlterField(
            model_name='buysdocument',
            name='provider_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='customer_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
        ),
    ]
