# Generated by Django 4.1.7 on 2023-04-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_documentsitems_buy_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsitems',
            name='buy_document',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.buysdocument'),
        ),
        migrations.AlterField(
            model_name='documentsitems',
            name='sale_document',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.salesdocument'),
        ),
    ]
