# Generated by Django 4.1.7 on 2023-04-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_alter_company_options_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_machine', models.CharField(blank=True, choices=[('1', 'Registradora con mem. fiscal'), ('2', 'Impresora fiscal'), ('3', 'Computadora con mem. fiscal')], max_length=30)),
                ('serial', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
