# Generated by Django 4.1.7 on 2023-04-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxmachine',
            options={'verbose_name': 'Tax machine', 'verbose_name_plural': 'Tax machines'},
        ),
    ]
