# Generated by Django 4.1.7 on 2023-04-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('providers', '0002_alter_provider_type_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ret_code',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
    ]
